//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilmsWebApi.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FilmsModelContainer : DbContext
    {
        public FilmsModelContainer()
            : base("name=FilmsModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Film> FilmSet { get; set; }
        public virtual DbSet<Country> CountrySet { get; set; }
        public virtual DbSet<CountryFilm> CountryFilmSet { get; set; }
        public virtual DbSet<ActorFilm> ActorFilmSet { get; set; }
        public virtual DbSet<Actor> ActorSet { get; set; }
        public virtual DbSet<Producer> ProducerSet { get; set; }
        public virtual DbSet<GenreFilm> GenreFilmSet { get; set; }
        public virtual DbSet<Genre> GenreSet { get; set; }
    }
}
