//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpertSystemDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsultationRule
    {
        public int Id { get; set; }
        public RuleWork Work { get; set; }
    
        public virtual Consultation Consultation { get; set; }
        public virtual Rule Rule { get; set; }
    }
}
