//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpertSystemDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Variable
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Question { get; set; }
        public string Reasoning { get; set; }
        public VariableType Type { get; set; }
    
        public virtual Domain Domain { get; set; }
    }
}
